name: Azure Static Web Apps CI/CD - Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Só dispara se houver mudanças no Frontend

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build_and_Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # REMOVEMOS 'cache: npm' PARA EVITAR O ERRO DE ARQUIVO DE BLOQUEIO AUSENTE NA RAIZ

      # PASSO NOVO E CRUCIAL: Instalação das dependências do Frontend
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./frontend 

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Detalhes da Compilação
          app_location: "/frontend" 
          api_location: "/backend"  
          output_location: "dist"